import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Braces, GitBranch, Fingerprint, ScanLine, Layers, FileCheck2, ChevronRight } from 'lucide-react';
import { ProductPreview } from '@/components/site/product-preview';
import { Cta } from '@/components/site/cta';

const features = [
  { icon: GitBranch, number: '01', title: 'Connect the dots.', text: 'Follow supported routes, handlers, and data lookups through a readable security graph.', link: 'Explore the graph' },
  { icon: Fingerprint, number: '02', title: 'See the evidence.', text: 'Inspect the exact source locations behind potential authorization, injection, and credential issues.', link: 'Inside a finding' },
  { icon: Layers, number: '03', title: 'Bring your context.', text: 'Add product documents and let a local model help explain what the application appears to do.', link: 'Meet your workspace' },
];
export default function LandingPage() {
  return <main id="main-content" className="marketing-page">
    <section className="landing-hero dark-section"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><span className="release-pill"><span /> YOUR CODE, IN CONTEXT <ChevronRight size={12} /></span><h1>Trusted findings.<br />Safer <span>Software.</span></h1><p>Security findings are only the beginning. Connect your code, its context, and the evidence—so you can decide what matters.</p><div className="hero-actions"><Link href="/workspace" className="button button-primary">Analyze a repository <ArrowUpRight size={18} /></Link><Link href="/product" className="button button-dark-outline">Explore the product <ArrowRight size={17} /></Link></div><small>Local-first. Evidence-led. Human-reviewed.</small></div><div className="hero-preview"><ProductPreview /></div><div className="hero-bottom"><span>FROM SOURCE TO UNDERSTANDING</span><span>Built for the people who ship code <ArrowRight size={14} /></span></div></section>
    <section className="technology-strip" aria-label="Supported ecosystem"><span>MADE FOR YOUR STACK</span><div><Braces size={21} /> JavaScript</div><div><span className="tech-monogram">TS</span> TypeScript</div><div>express<span className="text-muted">.js</span></div><div><span className="tech-monogram">◇</span> Ollama</div><div><GitBranch size={20} /> GitHub</div></section>
    <section className="section-container intro-section" data-reveal><div><span className="kicker">THE BIGGER PICTURE</span><h2>Don’t just find a risk.<br /><span className="text-muted">Understand why it matters.</span></h2></div><p>Invaria turns a public repository into a connected view of its code and potential security issues. Clear evidence and product context bring you closer to an informed decision.</p></section>
    <section className="section-container feature-grid" aria-label="Product features">{features.map(({ icon: Icon, ...f }) => <article key={f.number} className="feature-card" data-reveal><div className="feature-top"><Icon size={25} /><span>{f.number}</span></div><h3>{f.title}</h3><p>{f.text}</p><Link href="/product" className="text-link">{f.link}<ArrowUpRight size={16} /></Link></article>)}</section>
    <section className="section-container workflow-section" data-reveal><div className="section-heading"><span className="kicker">A CLEAR PATH FORWARD</span><h2>From repository<br />to a reasoned review.</h2><p>A focused workflow. A traceable result.</p></div><div className="workflow-steps">{[{ icon: ScanLine, title: 'Bring the source.', text: 'Choose a public GitHub repository or a bundled fixture. Add documents for business context.' }, { icon: GitBranch, title: 'Follow the connections.', text: 'See supported endpoints, data access, and the source evidence behind each potential finding.' }, { icon: FileCheck2, title: 'Make the call.', text: 'Review, confirm, or dismiss findings. Save your reasoning and export the report.' }].map(({ icon: Icon, title, text }, i) => <article key={title}><span className="step-number">0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div><Icon size={22} /></article>)}</div></section>
    <section className="proof-section"><div className="section-container" data-reveal><div className="section-heading"><span className="kicker">SMALL SCOPE. VISIBLE EVIDENCE.</span><h2>Built to be inspected.</h2><p>Developer preview capabilities. No inflated promises.</p></div><div className="proof-grid"><div><strong>3<span> / checks</span></strong><p>Authorization, injection & credentials</p></div><div><strong>6<span> / fixtures</span></strong><p>Vulnerable and fixed test examples</p></div><div><strong>2<span> / exports</span></strong><p>JSON and Markdown reports</p></div><div><strong>100<span>% local AI</span></strong><p>Optional model inference through Ollama</p></div></div></div></section>
    <div className="section-container"><Cta /></div>
  </main>;
}
