import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, Check, GitBranch, FileSearch, Sparkles } from 'lucide-react';
import { ProductPreview } from '@/components/site/product-preview';
import { Cta } from '@/components/site/cta';
export const metadata: Metadata = { title: 'Product — Invaria', description: 'Explore the business-risk and technical-evidence workspace powered by INVARIANT.' };
export default function ProductPage() {
  return <main id="main-content" className="marketing-page"><section className="page-hero dark-section"><span className="kicker">BUSINESS RISK, WITH TECHNICAL PROOF</span><h1>From a codebase<br />to a <span>clear business decision.</span></h1><p>One scan produces a business-risk dashboard for product leaders and a technical-evidence dashboard for the people who need to verify it.</p><Link href="#live-workspace" className="button button-primary">Try the local preview <ArrowUpRight size={18} /></Link></section><section className="section-container product-showcase" data-reveal><ProductPreview /><p className="preview-caption">Illustrative workspace. Findings remain potential risks until a reviewer confirms them.</p></section><section className="section-container walkthrough">{[{ icon: Sparkles, title: 'Start with business risk.', text: 'A local Gemma overview explains the product and the possible operational consequence of each potential risk. It is advisory, visibly caveated, and never source evidence.', details: ['Business-risk dashboard by default', 'Product context from code and documents', 'Potential outcomes, never incident claims'] }, { icon: GitBranch, title: 'Follow the product path.', text: 'INVARIANT links supported entry points, inputs, sensitive operations, and data access before it asks a reviewer to consider a risk.', details: ['Route-to-operation relationships', 'Policy and invariant coverage', 'Visible assumptions and limits'] }, { icon: FileSearch, title: 'Verify the evidence.', text: 'Move into the technical dashboard to inspect source locations, the security graph, coverage, remediation, and review decisions.', details: ['Evidence gate per finding', 'Confirm or dismiss with a note', 'Export JSON or Markdown'] }].map(({ icon: Icon, ...item }, index) => <article key={item.title} data-reveal><div className="walkthrough-visual"><span className="giant-step">0{index + 1}</span><Icon size={72} strokeWidth={1} /></div><div><span className="kicker">STEP 0{index + 1}</span><h2>{item.title}</h2><p>{item.text}</p><ul>{item.details.map(detail => <li key={detail}><Check size={16} />{detail}</li>)}</ul></div></article>)}</section><section id="live-workspace" className="live-section dark-section"><div className="section-container"><div className="section-heading"><span className="kicker">NOT A SLIDE DECK</span><h2>The real workspace.<br />Ready when you are.</h2><p>This is your local application. Actions here create real scans and saved reviews.</p><Link href="/workspace?lens=business" className="text-link">Open business risk <ArrowUpRight size={17} /></Link></div><div className="live-frame"><iframe src="/workspace?embed=1&lens=business" title="Live Invaria analysis workspace" loading="lazy" /></div></div></section><div className="section-container"><Cta title={'Better context.\nMore confident decisions.'} /></div></main>;
}
