import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, Check, GitBranch, FileSearch, Sparkles } from 'lucide-react';
import { ProductPreview } from '@/components/site/product-preview';
import { Cta } from '@/components/site/cta';
export const metadata: Metadata = { title: 'Product — Invaria', description: 'Explore the evidence-first security workspace, graph and local AI product overview.' };
export default function ProductPage() {
  return <main id="main-content" className="marketing-page"><section className="page-hero dark-section"><span className="kicker">MEET YOUR NEW PERSPECTIVE</span><h1>From a codebase<br />to a <span>clear picture.</span></h1><p>One workspace for the product context, source evidence, and decisions that make security review useful.</p><Link href="#live-workspace" className="button button-primary">Try the live workspace <ArrowUpRight size={18} /></Link></section><section className="section-container product-showcase" data-reveal><ProductPreview /><p className="preview-caption">Illustrative authorization fixture. Your actual findings depend on the scanned source.</p></section><section className="section-container walkthrough">{[{ icon: Sparkles, title: 'Start with the product.', text: 'A plain-language overview explains what the application appears to do. Uploaded documents add business context, with limitations made visible.', details: ['Generated with your local model', 'Saved with the scan', 'Separate from security evidence'] }, { icon: GitBranch, title: 'See how it connects.', text: 'Move from supported Express endpoints to functions and data lookups. The security graph gives each potential issue a place in the wider application.', details: ['Route-by-route exploration', 'Linked code locations', 'Explicit coverage limits'] }, { icon: FileSearch, title: 'Review with a reason.', text: 'Open a finding to inspect its code, assumptions, and suggested remediation. Record your decision so the next review starts with context.', details: ['Confirm or dismiss with a note', 'Optional Gemma evidence review', 'Export JSON or Markdown'] }].map(({ icon: Icon, ...item }, index) => <article key={item.title} data-reveal><div className="walkthrough-visual"><span className="giant-step">0{index + 1}</span><Icon size={72} strokeWidth={1} /></div><div><span className="kicker">STEP 0{index + 1}</span><h2>{item.title}</h2><p>{item.text}</p><ul>{item.details.map(detail => <li key={detail}><Check size={16} />{detail}</li>)}</ul></div></article>)}</section><section id="live-workspace" className="live-section dark-section"><div className="section-container"><div className="section-heading"><span className="kicker">NOT A SLIDE DECK</span><h2>The real workspace.<br />Ready when you are.</h2><p>This is your local application. Actions here create real scans and saved reviews.</p><Link href="/workspace" className="text-link">Open in full screen <ArrowUpRight size={17} /></Link></div><div className="live-frame"><iframe src="/workspace?embed=1" title="Live Invaria analysis workspace" loading="lazy" /></div></div></section><div className="section-container"><Cta title={'Better context.\nMore confident decisions.'} /></div></main>;
}
